# Generated by Django 2.2.16 on 2022-06-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220628_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите ваше изображение', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
