# Generated by Django 2.2.16 on 2022-11-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220919_2341'),
        ('posts', '0003_post_image'),
        ('posts', '0018_auto_20220621_1956'),
        ('posts', '0014_follow'),
        ('posts', '0011_auto_20220517_2016'),
        ('posts', '0008_auto_20220630_1414'),
        ('posts', '0014_auto_20220704_1819'),
    ]

    operations = [
    ]
