# Generated by Django 2.2.16 on 2022-11-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20221121_2019'),
        ('posts', '0015_auto_20221107_2136'),
        ('posts', '0013_auto_20220712_1458'),
        ('posts', '0014_auto_20221111_0459'),
    ]

    operations = [
    ]
